### ISSUE TITLE
bug "minitwitdb" does not exist

### ISSUE THREAD

**Issue by dmdequin** [ContainerMaintainers/MiniTwit-Golang#103]
When running `docker-compose up` (see discord for full command) getting error:
`FATAL:  database "minitwitdb" does not exist`

- [ ] Able to run above command with the application booting up as expected

**Comment by dmdequin** [comment]
The docker-compose.yml line 19. Change the database name to "minitwit-db", and the error will go away.

**Comment by sf-pear** [comment]
Can we close this?
