### ISSUE TITLE
Set up pipeline

### ISSUE THREAD

**Issue by adamjhr** [ContainerMaintainers/MiniTwit-Golang#34]
Set up CI/CD pipeline using github actions (a github workflow). The one from the exercises can be adapted to fit our needs.
Update it also so it runs the different tests we have (i.e. both minitwit_test.go and minitwit_sim_api_test.py)

https://raw.githubusercontent.com/itu-devops/lecture_notes/master/sessions/session_04/images/CICD_Setup.png

# Acceptance Criteria
 - Working github workflow
 - The tests are run when pushing to the main branch
 - The application is compiled and the image is pushed to a artefact registry
 - Deploy from the artefact registry to the cloud

**Comment by sf-pear** [comment]
Tests are not yet running, but rets is done, closing this.
