### ISSUE TITLE
Set up monitoring

### ISSUE THREAD

**Issue by Day0r** [ContainerMaintainers/MiniTwit-Golang#66]
- [ ] Setup prometheus container
- [ ] Connect to minitwit application using the golang client library

[link to tasks](https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_06/README_TASKS.md)

# Acceptance Criteria
- Data is collected in prometheus server

**Comment by sf-pear** [comment]
Duplicated #72. This is already done so I'm closing it.
