### ISSUE TITLE
Link to user timeline

### ISSUE THREAD

**Issue by PatrickMatthiesen** [ContainerMaintainers/MiniTwit-Golang#71]
It would be nice with a way to be redirected to a message authors TimeLine.
This would probably be good to do when adding the usernames of authors to the messages :)

**Comment by dmdequin** [comment]
As far as I understand, we have this in place. There is:
- Usernames of authors in messages.
- The usernames are links to their timeline.

![Image](https://user-images.githubusercontent.com/62339718/233835846-009e35c4-94c0-43cf-8011-fcbc09495c9a.png)
